# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_privatemsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
